from db.serverPostgres import db

class ItemEmision(db.Model):    
    __tablename__ = 'itemEmision'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nroCliente = db.Column(db.Text)
    titular = db.Column(db.Text)
    calle = db.Column(db.Text)
    idEmision = db.Column(db.Integer, db.ForeignKey('emision.id'))
    sucursal = db.Column(db.Text)
    planTurno = db.Column(db.Text)
    radio = db.Column(db.Text)
    ruta = db.Column(db.Text)
    distribuidor = db.Column(db.Text)
    estadoPieza = db.Column(db.Text)
    obsInterna = db.Column(db.Text)
    obsVisita = db.Column(db.Text)
    fechaDistrib = db.Column(db.Date)
    horaDistrib = db.Column(db.Time)
    geoCliente = db.Column(db.Text)
    geoVisita = db.Column(db.Text)
    foto = db.Column(db.Text)
    idGrupoCliente = db.Column(db.Integer, db.ForeignKey('grupoCliente.id'))
    lote = db.Column(db.Text)
    legajo = db.Column(db.Text)
    tipoDePieza = db.Column(db.Text)
    localidad = db.Column(db.Text)
    firma = db.Column(db.Text)
    altura = db.Column(db.Text)
    fechaEmision = db.Column(db.Text)