from db.serverPostgres import db

class ItemEmision(db.Model):    
    __tablename__ = 'itemEmision'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    idEmision = db.Column(db.Integer, db.ForeignKey('emision.id'))
    nroCliente = db.Column(db.Text)
    titular = db.Column(db.Text)
    calle = db.Column(db.Text)
    altura = db.Column(db.Text)
    localidad = db.Column(db.Text)
    planTurno = db.Column(db.Text)
    sucursal = db.Column(db.Text)
    radio = db.Column(db.Text)
    lote = db.Column(db.Text)
    recorridoH = db.Column(db.Text)
    ruta = db.Column(db.Text)
    estadoPieza = db.Column(db.Text)
    legajo = db.Column(db.Text)
    distribuidor = db.Column(db.Text)
    supervisor = db.Column(db.Text)
    fechaDistrib = db.Column(db.Date)
    horaDistrib = db.Column(db.Time)
    obsInterna = db.Column(db.Text)
    obsVisita = db.Column(db.Text)
    foto = db.Column(db.Text)
    firma = db.Column(db.Text)
    geoVisita = db.Column(db.Text)
    fechaIngreso = db.Column(db.Text)
    fechaEmision = db.Column(db.Text)
    fechaCertificacion = db.Column(db.Text)
    fechaAsignacion = db.Column(db.Text)
    tipoDePieza = db.Column(db.Text)
    codigoBarras = db.Column(db.Text)
    geoCliente = db.Column(db.Text)
    idGrupoCliente = db.Column(db.Integer, db.ForeignKey('grupoCliente.id'))
    estadoMetro = db.Column(db.Text)
    avisoMetro = db.Column(db.Text)
    fechaVencimientoMetro = db.Column(db.Text)
    importeMetro = db.Column(db.Text)
    vencimiento = db.Column(db.Text)
    importe = db.Column(db.Text)
    comprobante = db.Column(db.Text)
    medidor = db.Column(db.Text)
    entreCalles = db.Column(db.Text)
    codigoPostal = db.Column(db.Text)
